// <auto-generated />
using HotelListing.Net6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.Net6.Migrations
{
    [DbContext(typeof(HotelDBContext))]
    [Migration("20220803050716_seedingData")]
    partial class seedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelListing.Net6.Data.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Bahama",
                            shortname = "BHM"
                        },
                        new
                        {
                            id = 2,
                            name = "Caribean",
                            shortname = "CRB"
                        },
                        new
                        {
                            id = 3,
                            name = "Greece",
                            shortname = "GRC"
                        });
                });

            modelBuilder.Entity("HotelListing.Net6.Data.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rating")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("countryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            adress = "Bahama Hotel International Address",
                            countryId = 1,
                            name = "Bahama Hotel International",
                            rating = 1.0
                        },
                        new
                        {
                            id = 2,
                            adress = "Bahama Hotel Leasure Hotel Address",
                            countryId = 1,
                            name = "Bahama Hotel Leasure Hotel",
                            rating = 5.0
                        },
                        new
                        {
                            id = 3,
                            adress = "Greece  Hotel Leasure Hotel Address",
                            countryId = 3,
                            name = "Greece Hotel Leasure Hotel",
                            rating = 4.0
                        });
                });

            modelBuilder.Entity("HotelListing.Net6.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Net6.Data.Country", "country")
                        .WithMany("Hotels")
                        .HasForeignKey("countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("HotelListing.Net6.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
